{% set name = "tabpy" %}
{% set version = "2.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tabpy-{{ version }}.tar.gz
  sha256: 84c34708e4e1c97aeb9f402cb9d57c7ec63b4a499cba2c8d7bda10eeaf5c1f08

build:
  entry_points:
    - tabpy=tabpy.tabpy:main
    - tabpy-user=tabpy.utils.tabpy_user:main
    - tabpy-deploy-models=tabpy.models.deploy_models:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pytest-runner
    - pip
    - setuptools
  run:
    - python >=3.8
    - cloudpickle
    - configparser
    - coverage
    - coveralls
    - docopt
    - future
    - genson
    - hypothesis
    - jsonschema
    - mock
    - nltk
    - numpy
    - pandas
    - pyopenssl
    - pytest
    - pytest-cov
    - requests
    - scipy
    - simplejson
    - scikit-learn
    - textblob
    - tornado
    - twisted
    - urllib3
    - pyarrow
    - libarrow-flight

test:
  imports:
    - tabpy
  commands:
    - pip check
    - tabpy --help
    - tabpy-user --help
  requires:
    - pip

about:
  home: https://github.com/tableau/TabPy
  summary: Web server Tableau uses to run Python scripts.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
